# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # HTTP Port (kept published so Caddy on the other host can reach this instance)
      - "314:80/tcp"
    networks:
      - proxy
    environment:
      TZ: 'America/Detroit'
      FTLCONF_webserver_api_password: $PASSWORD
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - ./etc:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

networks:
  proxy:
    external: true
