services:
  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    restart: unless-stopped
    networks:
      - proxy
    extends:
      file: hwaccel.ml.yml
      # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
      service: openvino-wsl
    #volumes:
    #- model-cache:/cache
    # devices:
    #- /dev/dri:/dev/dri
    #healthcheck:
    # disable: false

networks:
  proxy:
    external: true
