services:
  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
    devices:
      - /dev/sda
      - /dev/sdb
    cap_add:
      - SYS_RAWIO # required for SMART data
      - SYS_ADMIN # required for NVMe SMART data
    healthcheck:
      test: ['CMD', '/agent', 'health']
      interval: 120s
    environment:
      LISTEN: ${LISTEN}
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: ${HUB_URL}
