services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy
    environment:
      # Allow inbound connections from the proxy network to the qBitTorrent UI
      - FIREWALL_INPUT_PORTS=8080
    volumes:
      - /config:/gluetun
    env_file: .env
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:8080:8080"
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    env_file: .env
    volumes:
      - ./config:/config
      - ${DOWNLOADS_PATH}:/downloads # optional
    network_mode: "service:gluetun"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      start_period: 30s
      interval: 60s
      timeout: 5s
    depends_on:
      gluetun:
        condition: service_healthy

networks:
  proxy:
    external: true
