services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    networks:
      - proxy
    volumes:
      - ./radarr/config:/config
      - type: bind
        source: ${MEDIA_SOURCE}
        target: /media
      - type: bind
        source: ${DOWNLOADS_PATH}
        target: /downloads
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7878/ping || exit 1
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    networks:
      - proxy
    volumes:
      - ./sonarr/config:/config
      - type: bind
        source: ${MEDIA_SOURCE}
        target: /media
      - type: bind
        source: ${DOWNLOADS_PATH}
        target: /downloads
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8989/ping || exit 1
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    networks:
      - proxy
    volumes:
      - ./prowlarr/config:/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9696/ping || exit 1
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3

networks:
  proxy:
    external: true
