services:
  beszel:
    image: henrygd/beszel
    container_name: beszel-hub
    restart: unless-stopped
    environment:
      - APP_URL=https://beszel.kevinkraydi.ch
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
